# Generated by Django 4.1.2 on 2022-12-09 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidentreport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentremark',
            name='incident_location',
            field=models.BooleanField(default=False),
        ),
    ]
