# Generated by Django 4.1.2 on 2022-12-10 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('incidentreport', '0002_alter_incidentremark_incident_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('is_incident_verified', models.BooleanField(default=False)),
                ('otp', models.CharField(max_length=6)),
                ('uid', models.CharField(default='<function uuid4 at 0x101c80310>', max_length=200)),
                ('incident_general', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='incidentreport.incidentgeneral')),
                ('user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
