# Generated by Django 4.1.2 on 2022-12-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidentreport', '0003_incidentotp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentotp',
            name='uid',
        ),
        migrations.AlterField(
            model_name='incidentotp',
            name='otp',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
