# Generated by Django 4.1.2 on 2022-12-10 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidentreport', '0005_incidentgeneral_upload_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentgeneral',
            name='movement_code',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='incidentremark',
            name='action_taken',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
