# Generated by Django 4.1.2 on 2022-12-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidentreport', '0006_alter_incidentgeneral_movement_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentgeneral',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='incidentgeneral',
            name='time',
            field=models.TimeField(),
        ),
    ]
