# Generated by Django 4.1.2 on 2022-12-17 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('incidentreport', '0007_alter_incidentgeneral_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentgeneral',
            name='user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incident_generals', to=settings.AUTH_USER_MODEL),
        ),
    ]
