# Generated by Django 4.1.2 on 2022-12-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_id', models.CharField(blank=True, max_length=12)),
                ('csv_file', models.FileField(null=True, upload_to='csvs')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
