# Generated by Django 4.1.2 on 2022-12-11 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import generate_report.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('generate_report', '0002_uploadfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='csv_file',
            field=models.FileField(null=True, upload_to=generate_report.models.incident_image_upload_path),
        ),
    ]
