# Generated by Django 4.1.2 on 2022-12-14 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('image_pie', models.ImageField(blank=True, upload_to='reports')),
                ('image_bar', models.ImageField(blank=True, upload_to='reports')),
                ('image_dot', models.ImageField(blank=True, upload_to='reports')),
                ('image_heat', models.ImageField(blank=True, upload_to='reports')),
                ('image_map', models.ImageField(blank=True, upload_to='reports')),
                ('remarks', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
            ],
        ),
    ]
