# Generated by Django 4.1.2 on 2022-12-09 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_remove_notification_incident_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='text_preview',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
